CREATE TABLESPACE "APPDAT" 
  LOGGING DATAFILE '/opt/oracle_11g/oradata/orcl/appdat.dbf' 
  SIZE 1024M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
  
CREATE TABLESPACE "APPIDX"
  LOGGING DATAFILE '/opt/oracle_11g/oradata/orcl/appidx.dbf' 
  SIZE 512M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
