CREATE MATERIALIZED VIEW LOG ON log
   WITH PRIMARY KEY, SEQUENCE (logtype_code,job_name,package_name,method_name,MESSAGE,UNIQ_SESSION_ID,FORMAT_ERROR_BACKTRACE,FORMAT_ERROR_STACK,FORMAT_CALL_STACK,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY);
