DROP user apps CASCADE;

CREATE USER apps
  PROFILE DEFAULT IDENTIFIED BY apps
  DEFAULT TABLESPACE APPDAT TEMPORARY TABLESPACE TEMP ACCOUNT UNLOCK;
  
GRANT CONNECT TO apps;
GRANT RESOURCE TO apps;

GRANT CREATE SESSION TO apps;
GRANT CREATE ANY INDEX TO apps;
GRANT CREATE ANY SEQUENCE TO apps;
GRANT CREATE ANY SYNONYM TO apps;
GRANT CREATE ANY TABLE TO apps;
GRANT CREATE ANY TRIGGER TO apps;
GRANT CREATE ANY VIEW TO apps;
GRANT CREATE PROCEDURE TO apps;
GRANT CREATE PUBLIC SYNONYM TO apps;
GRANT CREATE TRIGGER TO apps;
GRANT CREATE VIEW TO apps;
GRANT CREATE DATABASE LINK TO apps;
GRANT CREATE ANY directory TO apps;

GRANT ALTER ANY INDEX to apps;
GRANT ALTER ANY SEQUENCE TO apps;
GRANT ALTER ANY TABLE TO apps;
GRANT ALTER ANY TRIGGER TO apps;

GRANT DELETE ANY TABLE TO apps;

GRANT DROP ANY INDEX TO apps;
GRANT DROP ANY SEQUENCE TO apps;
GRANT DROP ANY TABLE TO apps;
GRANT DROP ANY TRIGGER TO apps;
GRANT DROP ANY VIEW TO apps;

GRANT INSERT ANY TABLE TO apps;
GRANT QUERY REWRITE TO apps;

GRANT SELECT ANY TABLE TO apps;
GRANT UNLIMITED TABLESPACE TO apps;
  


